### ISSUE TITLE
incorrect photo display

### ISSUE THREAD

**Issue by MOPOKO** [tansuluu/com#11]
- [x]  On the "Faculty" page, photos borders are not resized correctly ( Issue with bottom black lines )
![screenshot from 2018-09-14 11-39-01](https://user-images.githubusercontent.com/38830060/45531841-6d279480-b813-11e8-977a-9ea2217c3f07.png)
![screenshot from 2018-09-14 11-39-17](https://user-images.githubusercontent.com/38830060/45531843-6dc02b00-b813-11e8-877a-2fec889b01be.png)

**Comment by tansuluu** [comment]
Done!

**Comment by MOPOKO** [comment]
Please update link, so i can see the difference)
